from tkinter    import *
from tkinter    import ttk
from tkcalendar import Calendar, DateEntry

import tkinter  as tk
import sqlite3


                                 # diretorio do app
from janela.principal.composicao_principal import (
    CADAST_TEXT_NOME, CADASTRO_FRAME1HEIGHT, CADASTRO_FRAME1WIGHT, CADASTRO_FRAME1X, 
    CADASTRO_FRAME2Y, TAMANHO_WIDTH_JANELA, TAMANHO_HEIGHT_JANELA,

    MENUS_WIDTH, MENU_Y, MENU_HEIGHT, 

    COR_FUNDO_JANELA, COR_FUNDO_BOTAO_MENU_BAR, COR_BOTAO_FUNDO, COR_FUNDO_1,
    COR_FUNDO_2, COR_FUNDO_3,

    COR_ESCRITA_MENU_BAR, COR_ESCRITA1,

    NOME_NOVA_ALIANCA, 

    CADASTRAR, INFORMACOES, SOLTEIRO,

    TEXT_THUE, TEXT_FALSE,TEXT_SALVAR, TEXT_ATUALIZAR,

    NUM_0, NUM_1, NUM_2, NUM_3, NUM_4, NUM_5, NUM_6, 

    WIDGET_2, WIDGET_4, 

    CADASTRO_FRAME1X, CADASTRO_FRAME1WIGHT, CADASTRO_FRAME1HEIGHT,

    CADASTRO_FRAME2Y, CADASTRO_FRAME2W, CADASTRO_FRAME2H,

    CADAST_BOTAO_INSTITUICAO_X, CADAST_BOTAO_INSTITUICAO_Y,
    CADAST_BOTAO_INSTITUICAO_W, CADAST_BOTAO_INSTITUICAO_H,

     FRAME2_500,FRAME2_55, FRAME2_400,
    FRAME2_30,

    CADASTRO_SALVARX, CADASTRO_SALVARY,

    CADAST_TEXT_NOME
     
)