
TAMANHO_WIDTH_JANELA     = 1000

MENUS_WIDTH              = 130
MENU_Y                   = 10
MENU_HEIGHT              = 20

COR_FUNDO_JANELA         = '#C0C0C0' #cor Silver

COR_FUNDO_BOTAO_MENU_BAR = '#8B4513' # cor SaddleBrown
COR_ESCRITA_MENU_BAR     = '#FFFF00' # COR Yellow

NOME_NOVA_ALIANCA        = "NOVA ALIANÇA"

COR_BOTAO_FUNDO          = "#6A5ACD" # SlateBlue

CONFIGURACAO_BOTAO_INSTITUICAO_X      = 240
CONFIGURACAO_BOTAO_INSTITUICAO_Y      = 80
CONFIGURACAO_BOTAO_INSTITUICAO_WIDTH  = 150
CONFIGURACAO_BOTAO_INSTITUICAO_HEIGHT = 35

CONFIGURACOES_INSTITUICAO_L2_SALVAR = "SALVAR"
CONFIGURACOES_INSTITUICAO_L2_ATUALIZAR = "ATUALIZAR"

DB_THUE      = "Thue"
DB_FALSE     = "False"
DB_ATUALIZAR = "ATUALIZAR"
DB_SALVAR    = "SALVAR"

DB_0 = 0
DB_1 = 1
DB_2 = 2
DB_3 = 3
DB_4 = 4
DB_5 = 5
DB_6 = 6

DB_STR_1 = "1"
DB_STR_2 = "2"
DB_STR_3 = "3"
DB_STR_4 = "4"
DB_STR_5 = "5"
DB_STR_6 = "6"



 #self.sql_cursorr.execute("UPDATE '"+self.c+"' '"+self.cs+"' = '"+self.destroir_banco_1+"' WHERE cod = '"self.vf"' " )