
TAMANHO_WIDTH_JANELA     = 1300
TAMANHO_HEIGHT_JANELA    = 850

WIDGET_2     = 2
WIDGET_4     = 4

MENUS_WIDTH  = 130
MENU_Y       = 10
MENU_HEIGHT  = 25

COR_FUNDO_JANELA         = '#C0C0C0' #cor Silver

COR_FUNDO_BOTAO_MENU_BAR = '#8B4513' # cor SaddleBrown
COR_BOTAO_FUNDO          = "#6A5ACD" # SlateBlue
COR_FUNDO_1              = '#778899' # LightSlateGray
COR_FUNDO_2              = "#228B22" # ForestGreen



COR_ESCRITA_MENU_BAR = '#FFFF00' # COR Yellow
COR_ESCRITA1         = "#FFF5EE" # Seashell

NOME_NOVA_ALIANCA    = "NOVA ALIANÇA"

CADASTRO_FRAME2Y = 55 
CADASTRO_FRAME2W = 200
CADASTRO_FRAME2H = 30

CADASTRO_FRAME1X      = 20
CADASTRO_FRAME1WIGHT  = 150
CADASTRO_FRAME1HEIGHT = 30

CONFIGURACAO_BOTAO_INSTITUICAO_X      = 240
CONFIGURACAO_BOTAO_INSTITUICAO_Y      = 80
CONFIGURACAO_BOTAO_INSTITUICAO_WIDTH  = 150
CONFIGURACAO_BOTAO_INSTITUICAO_HEIGHT = 35

CONFIGURACAO_ENTRYX      = 20       
CONFIGURACAO_ENTRYY      = 85
CONFIGURACAO_ENTRYWIDGET = 200
CONFIGURACAO_ENTRYHEIGHT = 25

DB_THUE      = "Thue"
DB_FALSE     = "False"
DB_ATUALIZAR = "ATUALIZAR"
DB_SALVAR    = "SALVAR"

DB_0 = 0
DB_1 = 1
DB_2 = 2
DB_3 = 3
DB_4 = 4
DB_5 = 5
DB_6 = 6


 #self.sql_cursorr.execute("UPDATE '"+self.c+"' '"+self.cs+"' = '"+self.destroir_banco_1+"' WHERE cod = '"self.vf"' " )